version: '3.7'
services:
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: .
    image: DB_lab4/backend
    ports:
      - '3000:3000'
    links:
      - mongo-db

  client:
    build: client
    image: frontend
    ports:
      - '80:80'